### ISSUE TITLE
what is this ?

### ISSUE THREAD

**Issue by trphp** [gmonteeeiro/twitterbot#1]
I wonder what this is

**Comment by gmonteeeiro** [comment]
I'm creating a bot project for twitter.
The idea is to be a complete bot, from the account creation process to the tweeting, retweeting, etc.

For now, I'm in the process of creating a twitter account.

**Comment by trphp** [comment]
I would like to help you.I liked a project

**Comment by gmonteeeiro** [comment]
Yes you can! (Please help me hahaha)

**Comment by gmonteeeiro** [comment]
You can see the #2 issue, if you want

**Comment by trphp** [comment]
> Yes you can! (Please help me hahaha)

my goal is not to make you fall small, I just wondered the end of the project

**Comment by gmonteeeiro** [comment]
Pardon me, but are you using Google Translate? I can't understand your message
